name: Deploy to dev

on:
  workflow_call:
    inputs:
      GH_PR_MERGED:
        required: true
        type: boolean

jobs:
  cd:
    if: inputs.GH_PR_MERGED
    needs: ci
    name: deploy to develop
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: develop
    steps:
    
    - name: Test step ABC
      run: echo "Test step ABC..."
