name: Deploy to prod

on:
  workflow_call:
    inputs:
      GH_PR_MERGED:
        required: true
        type: boolean
jobs:
  cd:
    if: ${{ inputs.GH_PR_MERGED }} 
    name: cd to prod
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: production
    steps:

    - name: Test step ABC
      run: echo "Test step ABC..."