name: "Implement new release"

on:
  workflow_call:
    inputs:
      GH_VERSION:
        required: true
        type: string
        
jobs:
  cd:
    name: pre-release to staging
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: staging

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          ref: release/${{ inputs.GH_VERSION }}

    - name: Test step ABC
      run: echo "Test step ABC..."