name: Deploy to dev

on:
  workflow_call:
    inputs:
      GH_PR_MERGED:
        required: true
        type: boolean
    secrets:
      NPM_TOKEN:
        required: true
      
jobs:
  ci:
    if: inputs.GH_PR_MERGED
    name: ci
    runs-on: ubuntu-latest
    timeout-minutes: 60    
    strategy:
      matrix:
        node-version: [14.x]
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Code build
      run: npm ci

    - name: Run unit tests

      run: npm test

    - name: Run lint
      run: npm run lint