name: Build & Test

on:
  workflow_call:
    inputs:
      HAS_UNIT_TEST:
        required: true
        type: boolean
      GH_BASE_REF:
        required: true
        type: string
      GH_HEAD_REF:
        required: true
        type: string
      NODE_VERSION:
        required: true
        type: string
      S3_BUCKET:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      CLOUDFRONT_ID:
        required: true
        type: string
      REACT_APP_SENTRY_API_URL:
        required: true
        type: string
      REACT_APP_API_URL:
        required: true
        type: string
      REACT_APP_LOAN_API_URL:
        required: true
        type: string
      REACT_APP_API_URL_NOTIFICATIONS_OLD:
        required: true
        type: string
      REACT_APP_API_URL_NOTIFICATIONS:
        required: true
        type: string
      ESLINT_NO_DEV_ERRORS:
        required: true
        type: boolean
      DISABLE_ESLINT_PLUGIN:
        required: true
        type: boolean
      REACT_APP_ENVIRONMENT:
        required: true
        type: string
      REACT_APP_LOAN_API_URL_V2:
        required: true
        type: string
      REACT_APP_TRADING_API_URL_V2:
        required: true
        type: string
      REACT_APP_PINGDOM_SCRIPT:
        required: true
        type: string
      REACT_APP_PINGDOM_SCRIPT_INTEGRITY:
        required: true
        type: string
      REACT_APP_DISABLE_BLACKLIST:
        required: true
        type: boolean
      REACT_APP_DISABLE_PAYMENT_FREQUENCY:
        required: true
        type: boolean
      REACT_APP_DISABLE_REQUEST_CREATE_INSTITUTION_VIEW:
        required: true
        type: boolean
      REACT_APP_DISABLE_SPEED_UP:
        required: true
        type: boolean
      REACT_APP_BLOCKPASS_CLIENT_ID:
        required: true
        type: string
      REACT_APP_GOOGLE_CAPTCHA_SECRET_KEY:
        required: true
        type: string
      GIT_PKG_AUTH_TOKEN:
        required: true
        type: string
      GENERATE_SOURCEMAP:
        required: true
        type: boolean
      CI:
        required: true
        type: boolean

    secrets:
      NPM_TOKEN:
        required: true

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate PR origin branch to develop
        if: ${{ inputs.GH_BASE_REF == 'develop' && (!startsWith(inputs.GH_HEAD_REF, 'feature/') && !startsWith(inputs.GH_HEAD_REF, 'enhancement/') && !startsWith(inputs.GH_HEAD_REF, 'refactor/') && !startsWith(inputs.GH_HEAD_REF, 'fix/') && !startsWith(inputs.GH_HEAD_REF, 'migration/') && !startsWith(inputs.GH_HEAD_REF, 'release/') && !startsWith(inputs.GH_HEAD_REF, 'rc-feature/') && !startsWith(inputs.GH_HEAD_REF, 'backport/')) }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('origin branch from where the pull request is made is not known. Make sure to make a pull request from a known source branch, such as: feature/*, refactor/*, fix/*, migration/*, release/*, rc-feature/*, backport/*. For more details check the following documentation https://latticetrade.atlassian.net/l/cp/PUaek51t')
      
      - name: Validate origin branch to staging
        if: ${{ inputs.GH_BASE_REF == 'staging' && (!startsWith(inputs.GH_HEAD_REF, 'develop') && !startsWith(inputs.GH_HEAD_REF, 'hotfix/') && !startsWith(inputs.GH_HEAD_REF, 'main') && !startsWith(inputs.GH_HEAD_REF, 'release/') && !startsWith(inputs.GH_HEAD_REF, 'backport/')) }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('origin branch from where the pull request is made is not known. Make sure to make a pull request from a known source branch, such as: develop, hotfix/*, main, release/*, backport/*. For more details check the following documentation https://latticetrade.atlassian.net/l/cp/PUaek51t')
      
      - name: Validate origin branch to main
        if: ${{ inputs.GH_BASE_REF == 'main' && (!startsWith(inputs.GH_HEAD_REF, 'staging') && !startsWith(inputs.GH_HEAD_REF, 'hotfix/')) }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('origin branch from where the pull request is made is not known. Make sure to make a pull request from a known source branch, such as: staging, hotfix/*. For more details check the following documentation https://latticetrade.atlassian.net/l/cp/PUaek51t')


      - name: Use cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-frontend

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v3
        with:
            node-version: ${{ inputs.NODE_VERSION }}
            registry-url: https://registry.npmjs.org/

      - name: Code build
        run: npm ci

      - name: Run unit tests
        if: inputs.HAS_UNIT_TEST
        run: npm test

      - name: Run lint
        run: npm run lint
