name: Deploy to prod

on:
  workflow_call:
    inputs:
      GH_PR_MERGED:
        required: true
        type: boolean

jobs:
  ci:
    if: ${{ inputs.GH_PR_MERGED }} 
    name: ci
    runs-on: ubuntu-latest
    timeout-minutes: 60    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Test step ABC
      run: echo "Test step ABC..."

