name: "Deploy to staging"

on:
  workflow_call:
    inputs:
      HAS_UNIT_TEST:
        required: true
        type: boolean
      GH_VERSION:
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  ci:
    #if: ${{ github.event.review.state == 'approved' }}
    needs: draft-new-release
    name: ci
    runs-on: ubuntu-latest
    timeout-minutes: 60     
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          ref: release/${{ inputs.GH_VERSION }}
    
    - name: Use cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/setup-node@v1
      with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

    - name: Code build
      run: npm ci --ignore-scripts

      - name: Run unit tests
        if: inputs.HAS_UNIT_TEST
        run: npm test

    - name: Run lint
      run: npm run lint

