name: "Deploy to staging"

on:
  workflow_call:
    inputs:
      GH_VERSION:
        required: true
        type: string

jobs:
  ci:
    #if: ${{ github.event.review.state == 'approved' }}
    needs: draft-new-release
    name: ci
    runs-on: ubuntu-latest
    timeout-minutes: 60     
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          ref: release/${{ inputs.GH_VERSION }}
    
    - name: Test step ABC
      run: echo "Test step ABC..."
