name: draft new release

on:
  workflow_call:
    inputs:
      GH_BRANCH:
        required: true
        type: string
      GH_VERSION:
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  draft-new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }} 
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.GH_BRANCH }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release branch
        run: |
          git checkout -b release/${{ inputs.GH_VERSION }} ${{ inputs.GH_BRANCH }}
          git status

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Merge from main
        run: |
          git merge origin/main

      - name: Bump version in package.json
        run: yarn version --new-version ${{ inputs.GH_VERSION }} --no-git-tag-version

      - name: Commit manifest files
        id: make-commit
        run: |
          git add package.json
          git commit --message "Prepare release ${{ inputs.GH_VERSION }}"

          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Push new branch release
        run: git push origin release/${{ inputs.GH_VERSION }}

      - name: Push new branch hotfix
        run: |
          git checkout -b hotfix/${{ inputs.GH_VERSION }} release/${{ inputs.GH_VERSION }}
          git push origin hotfix/${{ inputs.GH_VERSION }}

      - name: Create PR release to main
        uses: Lattice-Trade/create-pull-request@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ inputs.GH_VERSION }}
          base: main
          title: Pre-release version ${{ inputs.GH_VERSION }}
          reviewers: ${{ github.actor }}
          body: |
            Hi @${{ github.actor }}!

            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            I've updated the changelog and bumped the versions in the manifest files in this commit: ${{ steps.make-commit.outputs.commit }}.

            Merging this PR will create a GitHub release and upload any assets that are created as part of the release build.

      - name: Create PR release to develop for backport
        uses: Lattice-Trade/create-pull-request@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ inputs.GH_VERSION }}
          base: develop
          title: Backport version ${{ inputs.GH_VERSION }}
          reviewers: ${{ github.actor }}
          body: |
            Hi @${{ github.actor }}!

            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            I've updated the changelog and bumped the versions in the manifest files in this commit: ${{ steps.make-commit.outputs.commit }}.

            Merging this PR will create a GitHub release and upload any assets that are created as part of the release build.