name: publish release

on:
  workflow_call:
    inputs:
      GH_PR_TITLE:
        required: true
        type: string
      GH_PR_HEAD_REF:
        required: true
        type: string
      GH_PR_HEAD_SHA:
        required: true
        type: string
      SENTRY_ENV:
        required: true
        type: string
      SENTRY_PROJECT:
        required: true
        type: string
    secrets:
      SENTRY_AUTH_TOKEN:
        required: true
      SENTRY_ORG:
        required: true

jobs:
  publish-release:
    name: publish new version release
    runs-on: ubuntu-latest
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: '${{ inputs.GH_PR_TITLE }}'

      - name: Extract version from branch name
        run: |
          BRANCH_NAME="${{ inputs.GH_PR_HEAD_REF }}"

      - name: Create Release
        uses: thomaseizinger/create-release@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{ inputs.GH_PR_HEAD_SHA }}
          tag_name: ${{ steps.split.outputs._2 }}
          name: ${{ steps.split.outputs._2 }}
          draft: false
          prerelease: false

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish Sentry release
        uses: getsentry/action-release@v1
        continue-on-error: true
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ inputs.SENTRY_PROJECT }}
          # SENTRY_URL: https://sentry.io/
        with:
          environment: ${{ inputs.SENTRY_ENV }}
          version: ${{ inputs.GH_PR_HEAD_SHA }}
          version_prefix: ${{ steps.split.outputs._2 }}
          