name: '📦 Test codebase'

on: 
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string
      HAS_UNIT_TEST:
        required: true
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Lattice-Trade/membrane-github-template-actions/.github/actions/typescript/install-deps.yml@feature/LM-9164-step-deduplication
        with:
          NODE_VERSION: ${{ inputs.NODE_VERSION }}
      - name: Run unit tests
        if: inputs.HAS_UNIT_TEST
        run: npm test