name: '📦 Create tag reading package.json'

on: 
  workflow_call:

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to develop
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0
      - name: Find last tag
        id: last-tag
        run: |
          git tag | cat
          echo result=$(git for-each-ref --sort=-creatordate --format '%(refname:short)' --count=1 refs/tags) >> $GITHUB_OUTPUT
        shell: bash
      - name: Search latest commits
        id: latest-commits
        run: echo result=$(git log ${{ steps.last-tag.outputs.result }}..HEAD --oneline) >> $GITHUB_OUTPUT
        shell: bash
      - name: Checkout to main
        uses: actions/checkout@v3
      - name: Pull version from package.json
        id: read-package
        run: |
          echo version=$(jq -r .version package.json) >> $GITHUB_OUTPUT
          echo line=$(cat package.json | grep '"version":.*,') >> $GITHUB_OUTPUT
        shell: bash
      - name: Create changelog
        run: |
          FILE=${{ github.workspace }}-CHANGELOG.txt
          cat <<EOF >$FILE
          ## Changes
          ${{ steps.latest-commits.outputs.result }}

          ## Compare
          $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/compare/${{ steps.last-tag.outputs.result }}...v${{ steps.read-package.outputs.version }}
          EOF
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          name: "v${{ steps.read-package.outputs.version }}"
          tag_name: "v${{ steps.read-package.outputs.version }}"
          target_commitish: main
          token: ${{ secrets.RELEASE_TOKEN }}