name: '📦 Lint codebase'

on: 
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: Lattice-Trade/membrane-github-template-actions/composite-actions/npm/install@staging
        with:
          NODE_VERSION: ${{ inputs.NODE_VERSION }}
      - name: Run lint
        continue-on-error: true
        run: npm run lint