name: '📦 Build application'

on: 
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Setup node
        uses: Lattice-Trade/membrane-github-template-actions/composite-actions/npm/setup-node@feature/{LM-10377}-PR-secret-fix
      - name: Download artifact of dependencies
        uses: actions/download-artifact@v3
        with:
          name: node_modules
          path: .
      - name: Build code
        run: npm run build