name: '📦 Test codebase'

on: 
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string
      HAS_UNIT_TEST:
        required: true
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Lattice-Trade/membrane-github-composite-actions/npm/check-tests@feature/LM-9164-step-deduplication
        id: check-tests
      - uses: Lattice-Trade/membrane-github-composite-actions/npm/install@feature/LM-9164-step-deduplication
        if: ${{ steps.check-tests.outputs.HAS_UNIT_TEST == 'true' }}
        with:
          NODE_VERSION: ${{ inputs.NODE_VERSION }}
      - name: Run unit tests
        if: inputs.HAS_UNIT_TEST
        run: npm test
      - name: run if tests DO NOT EXIST
        if: ${{ steps.check-tests.outputs.HAS_UNIT_TEST == 'false' }}
        run: ls -l
        shell: bash