name: '📦 Build application'

on: 
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Lattice-Trade/membrane-github-template-actions/.github/actions/typescript/install@feature/LM-9164-step-deduplication
        with:
          NODE_VERSION: ${{ inputs.NODE_VERSION }}
      - name: Build code
        run: npm run build