name: '📦 Test codebase'

on: 
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string
      HAS_UNIT_TEST:
        required: true
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Check if codebase tests are difined within package.json
        uses: Lattice-Trade/membrane-github-template-actions/composite-actions/npm/check-tests.v1@main
        id: check-tests
      - name: Setup node
        uses: Lattice-Trade/membrane-github-template-actions/composite-actions/npm/setup-node.v1@main
        with:
          NODE_VERSION: ${{ inputs.NODE_VERSION }}
      - name: Download and unzip dependencies artifact
        uses: Lattice-Trade/membrane-github-template-actions/composite-actions/git/download-artifact.v1@feature/{LM-10511}-npm-publishing
      - name: Run unit tests
        if: inputs.HAS_UNIT_TEST
        run: npm test
      # - name: Run unit tests
      #   if: ${{ steps.check-tests.outputs.HAS_UNIT_TEST == 'true' }}
      #   run: npm run test