name: Build & Publish to Registry

on:
  workflow_call:
    inputs:
      HAS_UNIT_TEST:
        required: false
        type: boolean
        default: false
      NODE_VERSION:
        required: true
        type: string
      USE_PAT:
        description: For repos that already published using Personal Access tokens, they should input a true. New repos will use $GITHUB_TOKEN.
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  packages: write
  repository-projects: write

jobs:
  install:
    uses: Lattice-Trade/membrane-github-template-actions/.github/workflows/typescript-install.yml@feature/{LM-10511}-npm-publishing
    with:
      NODE_VERSION: ${{ inputs.NODE_VERSION }}
    secrets: inherit

  lint:
    needs: install
    if: always() && needs.install.result == 'success'
    uses: Lattice-Trade/membrane-github-template-actions/.github/workflows/typescript-lint.yml@feature/{LM-10511}-npm-publishing
    with:
      NODE_VERSION: ${{ inputs.NODE_VERSION }}
    secrets: inherit

  test:
    needs: install
    if: always() && needs.install.result == 'success'
    uses: Lattice-Trade/membrane-github-template-actions/.github/workflows/typescript-test.yml@feature/{LM-10511}-npm-publishing
    with:
      NODE_VERSION: ${{ inputs.NODE_VERSION }}
      HAS_UNIT_TEST: ${{ inputs.HAS_UNIT_TEST }}
    secrets: inherit

  build:
    needs: [test, lint]
    if: |
      always() &&
      (needs.lint.result == 'success' && needs.test.result == 'success')
    uses: Lattice-Trade/membrane-github-template-actions/.github/workflows/typescript-build.yml@feature/{LM-10511}-npm-publishing
    with:
      NODE_VERSION: ${{ inputs.NODE_VERSION }}
      NPM_REGISTRY: npm.pkg.github.com
      NPM_SCOPE: "@${{ github.repository_owner }}"
      USE_PAT: ${{ inputs.USE_PAT }}
      # @Lattice-Trade should be default when using npm.pkg.github.com
      # https://github.com/actions/setup-node/blob/v3/action.yml#L20
    secrets: inherit