name: '📦 Build application'

on: 
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: Lattice-Trade/membrane-github-template-actions/composite-actions/npm/install@staging
        with:
          NODE_VERSION: ${{ inputs.NODE_VERSION }}
      - name: Build code
        run: npm run build